### ISSUE TITLE
progress tracking

### ISSUE THREAD

**Issue by andreasviglakis** [andreasviglakis/partyline#1]
- **Huang**
  - [x] reload dam style
  - [x] reload peak style
  - [x] reload city style
  - [x] reload town style
  - [x] reload rivers_ne_:schema:
  - [x] reload roads_hwm style
  - [x] reload urban areas style
  - [x] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [x] waterway labels
  - [x] waterbody labels
  - [x] landform labels
  - [x] marine labels
  - [x] country labels
  - [x] expressway shields
  - [x] lat/long labels
  - [x] update .qml files 

- **Heilongjian**
  - [x] reload dam style
  - [x] reload peak style
  - [x] reload city style
  - [x] reload town style
  - [x] reload rivers_ne_:schema:
  - [x] reload roads_hwm style
  - [x] reload urban areas style
  - [x] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [x] waterway labels
  - [x] waterbody labels
  - [x] landform labels
  - [x] marine labels
  - [x] country labels
  - [x] expressway shields
  - [x] lat/long labels 
  - [x] update .qml files 

- **Liao**
  - [x] reload dam style
  - [x] reload peak style
  - [x] reload city style
  - [x] reload town style
  - [x] reload rivers_ne_:schema:
  - [x] reload roads_hwm style
  - [x] reload urban areas style
  - [x] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [x] waterway labels
  - [x] waterbody labels
  - [x] landform labels
  - [x] marine labels
  - [x] country labels
  - [x] expressway shields
  - [x] lat/long labels 
  - [x] update .qml files 

- **Gobi**
  - [ ] reload dam style
  - [ ] reload peak style
  - [ ] reload city style
  - [ ] reload town style
  - [ ] reload rivers_ne_:schema:
  - [ ] reload roads_hwm style
  - [ ] reload urban areas style
  - [ ] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [x] waterway labels
  - [x] waterbody labels
  - [x] landform labels
  - [x] marine labels
  - [x] country labels
  - [x] expressway shields
  - [x] lat/long labels 
  - [x] update .qml files 

- **Hai**
  - [x] reload dam style
  - [x] reload peak style
  - [x] reload city style
  - [x] reload town style
  - [x] reload rivers_ne_:schema:
  - [x] reload roads_hwm style
  - [x] reload urban areas style
  - [x] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [x] waterway labels
  - [x] waterbody labels
  - [x] landform labels
  - [x] marine labels
  - [x] country labels
  - [x] expressway shields
  - [x] lat/long labels 
  - [x] update .qml files 

- **Zhu**
  - [x] define river highlights 
  - [x] city label placement
  - [x] airport label placement
  - [x] dam label placement
  - [ ] waterway labels
  - [ ] waterbody labels
  - [ ] landform labels
  - [ ] marine labels
  - [ ] country labels
  - [ ] expressway shields
  - [ ] lat/long labels 
  - [ ] update .qml files 

- **S China Sea**
  - [ ] define river highlights 
  - [ ] city label placement
  - [ ] airport label placement
  - [ ] dam label placement
  - [ ] waterway labels
  - [ ] waterbody labels
  - [ ] landform labels
  - [ ] marine labels
  - [ ] country labels
  - [ ] expressway shields
  - [ ] lat/long labels 
  - [ ] update .qml files
